# Site Info
title: '기록하고 정리하자'
tagline: '배하람의 삽질블로그'
description: '삽질하면서 발전 중인 블로그입니다.'
baseurl: ""
url: https://baeharam.github.io

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Haram Bae
  description: 배하람(Haram Bae)
  contact:
    github:    https://github.com/baeharam
    email:     gkfka6484@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { Flutter(플러터): '/blog/categories/#flutter-플러터' }
    - { Dart(다트): '/blog/categories/#dart-다트' }
    - { 알고리즘: '/blog/categories/#알고리즘' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-131473708-1' # leave blank if you don't want google analytics
disqus_short_name: 'baeharam-github-io'


# Use the following plug-ins
gems:
  - jekyll-paginate
