# Site Info
title: '기록하고 정리하자'
tagline: '코린이 스킬업 블로그'
description: '코린이 스킬업 블로그.'
baseurl: ""
url: https://bnkjeong.github.io

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: YOUNGCHEOL JEONG
  description: 정영철 (YoungCheol Jeong)
               BNK
  contact:
    github:    https://github.com/bnkjeong
    email:     koretoiles91@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { GIT: '/blog/categories/#git' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-131473708-1' # leave blank if you don't want google analytics
disqus_short_name: 'bnkjeong-github-io'


# Use the following plug-ins
gems:
  - jekyll-paginate
